import { NextRequest, NextResponse } from 'next/server';
import { generateUserFeed } from '@/lib/feed/rss-generator';
import { existsSync, readdirSync, statSync } from 'fs';
import path from 'path';
import os from 'os';

const AUDIO_DIR = path.join(os.tmpdir(), 'studypod-audio');

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  const { token } = await params;

  // Validate token format (UUID)
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(token)) {
    return NextResponse.json({ error: 'Invalid feed token' }, { status: 400 });
  }

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || `${request.nextUrl.protocol}//${request.nextUrl.host}`;

  // Try Supabase first
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (supabaseUrl && supabaseKey) {
    try {
      const { createClient } = await import('@supabase/supabase-js');
      const supabase = createClient(supabaseUrl, supabaseKey);

      // Look up user by feed token
      const { data: profile } = await supabase
        .from('profiles')
        .select('id, username, feed_token')
        .eq('feed_token', token)
        .single();

      if (!profile) {
        return NextResponse.json({ error: 'Feed not found' }, { status: 404 });
      }

      // Fetch user's flashcards with audio
      const { data: cards } = await supabase
        .from('flashcards')
        .select('id, front, back, explanation, audio_url, audio_storage_path, order_index, created_at, deck_id, decks(topic)')
        .eq('decks.user_id', profile.id)
        .not('audio_url', 'is', null)
        .order('created_at', { ascending: false })
        .limit(200);

      const feedCards = (cards || []).map((c: Record<string, unknown>) => ({
        id: c.id as string,
        front: c.front as string,
        back: c.back as string,
        explanation: (c.explanation as string) || '',
        audioUrl: (c.audio_url as string) || '',
        durationSeconds: 90,
        createdAt: c.created_at as string,
        deckTopic: ((c as Record<string, unknown>).decks as Record<string, string>)?.topic || 'Flashcards',
        orderIndex: (c.order_index as number) || 0,
      }));

      const xml = generateUserFeed({
        user: { username: profile.username, feedToken: token },
        cards: feedCards,
        baseUrl,
      });

      return new NextResponse(xml, {
        status: 200,
        headers: {
          'Content-Type': 'application/rss+xml; charset=utf-8',
          'Cache-Control': 'public, max-age=300',
        },
      });
    } catch (error) {
      console.error('Feed error (Supabase):', error);
    }
  }

  // Local fallback — serve all local audio files as a demo feed
  const mockCards = getLocalAudioCards(baseUrl);

  if (mockCards.length === 0) {
    const emptyFeed = generateUserFeed({
      user: { username: 'Demo User', feedToken: token },
      cards: [],
      baseUrl,
    });
    return new NextResponse(emptyFeed, {
      status: 200,
      headers: { 'Content-Type': 'application/rss+xml; charset=utf-8' },
    });
  }

  const xml = generateUserFeed({
    user: { username: 'Demo User', feedToken: token },
    cards: mockCards,
    baseUrl,
  });

  return new NextResponse(xml, {
    status: 200,
    headers: {
      'Content-Type': 'application/rss+xml; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
    },
  });
}

/** Scan /tmp/studypod-audio/ for local MP3s and create feed entries */
function getLocalAudioCards(baseUrl: string) {
  if (!existsSync(AUDIO_DIR)) return [];

  const files = readdirSync(AUDIO_DIR).filter((f) => f.endsWith('.mp3'));
  return files.map((filename, i) => {
    const stat = statSync(path.join(AUDIO_DIR, filename));
    const sizeBytes = stat.size;
    const estimatedDuration = Math.round(sizeBytes / 16000); // ~128kbps

    return {
      id: filename.replace('.mp3', ''),
      front: `Flashcard ${i + 1}`,
      back: 'Audio flashcard generated by studypod.ai',
      explanation: '',
      audioUrl: `/api/audio/${filename}`,
      durationSeconds: estimatedDuration,
      createdAt: stat.mtime.toISOString(),
      deckTopic: 'Study Session',
      orderIndex: i,
    };
  });
}
